.env.example, Makefile, buildspec.yml, scripts/deploy_kubernetes.sh
So that pods are deployed into namespaces
updates buildspec for pipeline
updates the script
=> adds kubernetes namespaces in kubernetes cluster 

scripts/deploy_kubernetes.sh
Accidently left this in when cleaning up
=> Remove line continuation \

Makefile, README.md, scripts/deploy_kubernetes.sh
- Added make targets to get pods and services
- Wrote up some documentation on how to get started. Would love any suggestions on how to improve this, writing is not my strong point!
- Refactored the deploy script a bit & got it to print out the Prometheus URL.
=> Some docs, some cleanup & some new make targets

kubernetes/infrastructure-monitoring/templates/azure-preprod-metrics-exporter-configmap.yaml, kubernetes/infrastructure-monitoring/templates/azure-preprod-metrics-exporter-deployment.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml, kubernetes/infrastructure-monitoring/values.yaml
Added ALZ pre-prod settings as part of on-boarding process.
=> Created preprod YAML files and updated references

kubernetes/infrastructure-monitoring/templates/alertmanager-deployment.yaml, kubernetes/infrastructure-monitoring/templates/cloudwatch-exporter-deployment.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-deployment.yaml, kubernetes/infrastructure-monitoring/templates/thanos-querier-deployment.yaml, kubernetes/infrastructure-monitoring/templates/thanos-receiver-deployment.yaml, kubernetes/infrastructure-monitoring/templates/thanos-store-deployment.yaml, kubernetes/infrastructure-monitoring/values.yaml
for help with local dev/ debugging
=> Added a flag to easily run all of the applications at debug log level

.env.example, buildspec.yml, kubernetes/infrastructure-monitoring/templates/azure-preprod-metrics-exporter-configmap.yaml, kubernetes/infrastructure-monitoring/templates/azure-preprod-metrics-exporter-deployment.yaml, kubernetes/infrastructure-monitoring/templates/azure-preprod-metrics-exporter-service.yaml, scripts/deploy_kubernetes.sh
All necessary changes to onboard a new Azure tenant to prometheus
=> Azure preprod onboarding

kubernetes/infrastructure-monitoring/templates/cloudwatch-exporter-configmap.yaml, scripts/deploy_kubernetes.sh
This PR adds a tag to the cloudwatch exporter image in the deploy script. 
Adds an `else if` to the cloudwatch exporter config map, which also applies the production config to pre-prod.
=> fixing cloudwatch exporter image

kubernetes/infrastructure-monitoring/templates/azure-devl-metrics-exporter-configmap.yaml
Removing some metrics which weren't working properly and adding in a couple of new ones.
=> :wrench: Updating Azure Metrics Exporter config.

kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml
Adding new target to blackbox-http job
https://alpha-fw.vpn.justice.gov.uk/
=> Adding new target to blackbox-http job

kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-jobs/_snmp-exporter-production.tpl, kubernetes/infrastructure-monitoring/values.yaml, scripts/deploy_kubernetes.sh
This PR will add SNMP scrape jobs to production prometheus. 
As part of this work we have parameterised IP addresses, fixed indentation, and used TPL to conditionally apply SNMP scrape jobs to production.
=> PTTP-6048/Migrate snmp exporter

kubernetes/infrastructure-monitoring/templates/cloudwatch-metrics/_default-metrics.tpl
This PR refactors the Cloudwatch exporter config file that is applied to the dev environment.
=> Pttp 8055/update default template

scripts/deploy_kubernetes.sh
This PR corrects the missing role ARNs for the production cloudwatch exporter config.
=> :recycle: refactor deploy script

kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-deployment.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-file-sd-configmap.yaml
Add file_sd config mapp
Add certificate services URLs to target yaml file
=> ✨ Add file service discovery

kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml
Processing is timing out after 5s on some sites which is causing issue
=> :wrench: add scrape_timeout and set to 15 seconds

.env.example, Makefile, README.md
This PR makes the necessary updates to bring this repo in line with the new aws-vault SSO best practices for the CloudOps team.
=> :recycle: Makefile, .env and Readme to reflect AWS SSO changes

README.md, documentation/cloudwatch-exporter.md
This PR adds docs for editing Cloudwatch exporter.
=> :memo: Add documentation for Cloudwatch Exporter

kubernetes/infrastructure-monitoring/templates/cloudwatch-metrics/_production-metrics-custom.tpl
We'd like to monitor some new metrics and change some of the existing
ones.
=> Add new NACS Cloudwatch metrics to Prometheus datasource

kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml
Adding the following endpoints to prometheus config:
gateway-c.internal.vpn.justice.gov.uk
gateway-f.internal.vpn.justice.gov.uk
Also removing replicate SOP OCI address
=> Pttp-9055 Monitor certificates PA 5260s firewalls in Farnham and Corsham

kubernetes/infrastructure-monitoring/templates/cloudwatch-metrics/_production-metrics-custom.tpl
This is a new metric in CloudWatch, make this available in the
dashboard.
=> NACS: Update custom metric for unknown CA

kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml
Increase timeout and move slow sites to new blackbox module with 30s timeout
=> :ambulance: create new bb job using new module

.github/ISSUE_TEMPLATE/cloud-operations-story.md
Adding Cloud Operations Story Template
=> :memo: Update issue template

kubernetes/infrastructure-monitoring/values.yaml
Switch off debug mode for logging now Thanos issue has been resolved.
=> :bug: Turn debug mode off

scripts/deploy_kubernetes.sh
An old variable remained in the script which needs to be removed.
=> :fire: remove old unbound variable

kubernetes/infrastructure-monitoring/templates/alertmanager-service.yaml, kubernetes/infrastructure-monitoring/templates/thanos-querier-service.yaml, kubernetes/infrastructure-monitoring/templates/thanos-receiver-service.yaml
The purpose of this PR is to resolve [this](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/issues/77) issue.
=> :lock: Locking down Thanos access, VPC CIDR block only

.env.example, buildspec.yml, documentation/cloudwatch-exporter.md, kubernetes/infrastructure-monitoring/templates/alertmanager-deployment.yaml, kubernetes/infrastructure-monitoring/templates/azure-devl-metrics-exporter-configmap.yaml, kubernetes/infrastructure-monitoring/templates/azure-preprod-metrics-exporter-configmap.yaml, kubernetes/infrastructure-monitoring/templates/cert-issuer.yaml, kubernetes/infrastructure-monitoring/templates/cloudwatch-exporter-deployment.yaml, kubernetes/infrastructure-monitoring/templates/cloudwatch-metrics/_production-metrics-custom.tpl, kubernetes/infrastructure-monitoring/templates/cloudwatch-metrics/_production-metrics.tpl, kubernetes/infrastructure-monitoring/templates/ingress-nginx-secure.yaml, kubernetes/infrastructure-monitoring/templates/ingress-nginx.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-deployment.yaml, kubernetes/infrastructure-monitoring/templates/prometheus-jobs/_snmp-exporter-production.tpl, kubernetes/infrastructure-monitoring/templates/thanos-compactor-deployment.yaml, kubernetes/infrastructure-monitoring/templates/thanos-querier-deployment.yaml, kubernetes/infrastructure-monitoring/templates/thanos-receiver-deployment.yaml, kubernetes/infrastructure-monitoring/templates/thanos-store-deployment.yaml, kubernetes/infrastructure-monitoring/values.yaml, scripts/deploy_kubernetes.sh
This PR cleans up the values.yaml file and favours a flat structure as recommended in the helm best practices documentation.  Values are also alphabetised and should (hopefully) be maintained as such 🤓
=> :recycle: bringing Values.yml in line with helm best practice

README.md, documentation/cloudwatch-exporter.md, documentation/prometheus-remote-write.md
This PR adds a how-to regarding writing metrics into the system from any prometheus instance.
=> 94-documentation-for-prometheus-remote-write

README.md
updated documentation to include steps on switching roles within the AWS console.
=> Switch role documentation

kubernetes/infrastructure-monitoring/templates/cloudwatch-metrics/_production-metrics-custom.tpl, kubernetes/infrastructure-monitoring/templates/cloudwatch-metrics/_production-metrics.tpl
This refactor is required due to upgrading the YACE image.
=> :recycle: Refactor roleArns

kubernetes/infrastructure-monitoring/templates/prometheus-deployment.yaml
Downgrading Prometheus a minor version until issues with Thanos are solved. This PR should fix #110
=> :arrow_down: downgrade Prometheus

scripts/deploy_kubernetes.sh
Deploy script to only run in production environment.
=> :hammer: Add conditional to deploy script

buildspec.yml, scripts/deploy_kubernetes.sh
Replace $ENV references with production, KUBERNETES_NAMESPACE renamed to lower case to signify a local variable. Updated build spec to create a development namespace in the production environment.
=> :hammer: Create development namespace in production environment.
